"Memory hardening in Parodus in exit scenarios"
xmidt-org/parodus pull request #424
Opened 2023-06-05 16:43 UTC by akif1716

Hi All, Please review the memory hardening patch in Parodus

2023-06-05 17:07 UTC, shilpa24balaji commented on src/config.c
> +         free(cfg->mtls_client_cert_path);
Set these pointers to null after free, as pointed by the "Use After free" vulnerability

2023-06-06 09:10 UTC, sadhyama commented on src/config.c
> +         free(cfg->mtls_client_cert_path);
yes try to fix security warnings reported .
Please submit PR to master branch as that is the latest branch which is pulled in yocto builds.

2023-06-06 09:11 UTC, sadhyama requested changes
Please submit PR to master branch as that is the latest branch which is pulled in yocto builds.

2023-07-20 05:36 UTC, shilpa24balaji commented
Merged as part of https://github.com/xmidt-org/parodus/pull/425

2023-07-20 05:36 UTC, closed without merging